name: Run Python Script

on:
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  # Pulling secrets from GitHub and setting them as environment variables
  client_id: ${{ secrets.CLIENT_ID }}
  client_secret: ${{ secrets.CLIENT_SECRET }}

jobs:
  run-python:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checks out the repository's code
      
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Ensure compatibility with your code's Python version

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Installs all dependencies listed in requirements.txt if it exists

      - name: Run Python Script
        env:
          CLIENT_ID: ${{ env.client_id }}
          CLIENT_SECRET: ${{ env.client_secret }}
        run: |
          python updated_main.py  # Replace this with your script name if different
