name: Deploy with GitHub Secret

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch

jobs:
  deploy-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Check out your repository code

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-dotenv

      - name: Run Deployment Script with Secret
        run: python deploy_script.py
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
