name: Deploy Streamlit App with Secrets

on:
  workflow_dispatch:  # Allows you to manually trigger the workflow

env:
  # Map GitHub secrets to environment variables
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checks out the code in the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Set the required Python version

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Install dependencies from requirements.txt if it exists

      - name: Run Streamlit App
        env:
          CLIENT_ID: ${{ env.CLIENT_ID }}
          CLIENT_SECRET: ${{ env.CLIENT_SECRET }}
        run: |
          streamlit run updated_main.py  # Replace with your Streamlit app filename
