name: Deploy Streamlit App

on:
  workflow_dispatch:  # Allows you to trigger the workflow manually

env:
  # Map GitHub secrets to environment variables
  CLIENT_ID: ${{ secrets.CLIENT_ID }}
  CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3  # Checks out the repository code

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'  # Define the Python version to use

      - name: Install Dependencies
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Installs dependencies from requirements.txt, if it exists

      - name: Run Streamlit App
        env:
          CLIENT_ID: ${{ env.CLIENT_ID }}
          CLIENT_SECRET: ${{ env.CLIENT_SECRET }}
        run: |
          streamlit run app.py  # Replace with your Streamlit app filename
